
from .py.grouping_extra_models import __name__
from .py.multi_lora_loader import (
    NODE_CLASS_MAPPINGS as MULTI_LORA_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as MULTI_LORA_NODE_DISPLAY_NAME_MAPPINGS,
)


NODE_CLASS_MAPPINGS = {
    **MULTI_LORA_NODE_CLASS_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **MULTI_LORA_NODE_DISPLAY_NAME_MAPPINGS,
}

WEB_DIRECTORY = "./web"
